name: Deploy docker image
on:
  push:
    branches:
      - 'master'
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: valitydev/action-deploy-docker@v2
        with:
          registry-username: ${{ github.actor }}
          registry-access-token: ${{ secrets.GITHUB_TOKEN }}

